package br.com.usinasantafe.cmm.common.utils

const val BASE_URL = "https://www.usinasantafe.com.br/cmmdev/view/"
const val BASE_SHARE_PREFERENCES = "config"
const val BASE_DB = "cmm.db"
const val VERSION_DB = 1

const val BASE_SHARE_PREFERENCES_SENHA = "senha"
const val BASE_SHARE_PREFERENCES_EQUIP = "equip"
const val BASE_SHARE_PREFERENCES_STATUS_ENVIO = "status_envio"

const val TB_ATIVIDADE = "tbatividade"
const val TB_BOCAL = "tbbocal"
const val TB_COMPONENTE = "tbcomponente"
const val TB_EQUIP = "tbequip"
const val TB_EQUIP_SEG = "tbequipseg"
const val TB_FRENTE = "tbfrente"
const val TB_FUNC = "tbfunc"
const val TB_ITEM_CHECKLIST = "tbitemchecklist"
const val TB_ITEM_OS_MECAN = "tbitemosmecan"
const val TB_LEIRA = "tbleira"
const val TB_OPER_MOTOMEC = "tbopermotomec"
const val TB_OS = "tbos"
const val TB_PARADA = "tbparada"
const val TB_PNEU = "tbpneu"
const val TB_PRESSAO_BOCAL = "tbpressaobocal"
const val TB_PRODUTO = "tbproduto"
const val TB_PROPRIEDADE = "tbpropriedade"
const val TB_R_ATIV_PARADA = "tbrativparada"
const val TB_R_EQUIP_ATIV = "tbrequipativ"
const val TB_R_EQUIP_PNEU = "tbrequippneu"
const val TB_R_FUNCAO_ATIV_PARADA = "tbrfuncaoativparada"
const val TB_R_OS_ATIV = "tbrosativ"
const val TB_SERVICO = "tbservico"
const val TB_TURNO = "tbturno"

const val TB_APONT_FERT = "tbapontfert"
const val TB_APONT_MM = "tbapontmm"
const val TB_BOLETIM_FERT = "tbboletimfert"
const val TB_BOLETIM_MM = "tbboletimmm"

const val WEB_FIELD_NRO_EQUIP = "nroEquip"
const val WEB_FIELD_NRO_OS = "nroOS"

const val WEB_FIND_EQUIP = "find-equip.php"
const val WEB_FIND_OS = "find-os.php"
const val WEB_FIND_R_OS_ATIV = "find-rosativ.php"
const val WEB_FIND_R_EQUIP_ATIV = "find-requipativ.php"
const val WEB_FIND_R_EQUIP_PNEU = "find-requippneu.php"

const val WEB_ALL_ATIVIDADE = "atividade.php"
const val WEB_ALL_BOCAL = "bocal.php"
const val WEB_ALL_COMPONENTE = "componente.php"
const val WEB_ALL_EQUIP_SEG = "equipseg.php"
const val WEB_ALL_FRENTE = "frente.php"
const val WEB_ALL_FUNC = "func.php"
const val WEB_ALL_ITEM_CHECKLIST = "itemchecklist.php"
const val WEB_ALL_ITEM_OS_MECAN = "itemosmecan.php"
const val WEB_ALL_LEIRA = "leira.php"
const val WEB_ALL_OPER_MOTOMEC = "opermotomec.php"
const val WEB_ALL_OS = "os.php"
const val WEB_ALL_PARADA = "parada.php"
const val WEB_ALL_PNEU = "pneu.php"
const val WEB_ALL_PRESSAO_BOCAL = "pressaobocal.php"
const val WEB_ALL_PRODUTO = "produto.php"
const val WEB_ALL_PROPRIEDADE = "propriedade.php"
const val WEB_ALL_R_ATIV_PARADA = "rativparada.php"
const val WEB_ALL_R_FUNCAO_ATIV_PARADA = "rfuncaoativparada.php"
const val WEB_ALL_R_OS_ATIV = "rosativ.php"
const val WEB_ALL_SERVICO = "servico.php"
const val WEB_ALL_TURNO = "turno.php"

const val WEB_SAVE_FERTIRRIGACAO = "savefertirrigacao.php"
const val WEB_SAVE_MOTOMEC = "savemotomec.php"