package br.com.usinasantafe.cmm.common.utils

const val BASE_URL = "https://www.usinasantafe.com.br/cmmdev/view/"
const val BASE_SHARE_PREFERENCES = "config"
const val BASE_DB = "cmm.db"
const val VERSION_DB = 1

const val BASE_SHARE_PREFERENCES_SENHA = "senha"
const val BASE_SHARE_PREFERENCES_EQUIP = "equip"

const val TB_ATIVIDADE = "tbatividade"
const val TB_BOCAL = "tbbocal"
const val TB_COMPONENTE = "tbcomponente"
const val TB_EQUIP = "tbequip"
const val TB_EQUIP_SEG = "tbequipseg"
const val TB_FRENTE = "tbfrente"
const val TB_FUNC = "tbfunc"
const val TB_ITEM_CHECKLIST = "tbitemchecklist"
const val TB_ITEM_OS_MECAN = "tbitemosmecan"
const val TB_LEIRA = "tbleira"
const val TB_MOTOMEC = "tbmotomec"
const val TB_OS = "tbos"
const val TB_PARADA = "tbparada"
const val TB_PNEU = "tbpneu"
const val TB_PRESSAO_BOCAL = "tbpressaobocal"
const val TB_PRODUTO = "tbproduto"
const val TB_PROPRIEDADE = "tbpropriedade"
const val TB_R_ATIV_PARADA = "tbrativparada"
const val TB_R_EQUIP_ATIV = "tbrequipativ"
const val TB_R_EQUIP_PNEU = "tbrequippneu"
const val TB_R_FUNCAO_ATIV_PARADA = "tbrfuncaoativparada"
const val TB_R_OS_ATIV = "tbrosativ"
const val TB_SERVICO = "tbservico"
const val TB_TURNO = "tbturno"

const val TB_APONT_FERT = "tbapontfert"
const val TB_APONT_MM = "tbapontmm"
const val TB_BOLETIM_FERT = "tbboletimfert"
const val TB_BOLETIM_MM = "tbboletimmm"